//! # End-to-End Quantum Language Model: Q-RENO Frontend + Scaled SRX Core
//!
//! Integrates:
//! 1. **Q-RENO Continuous Field Frontend:** Converts UTF-8 byte stream into topological quasi-particles $E_m \in \mathbb{R}^{d_{\text{model}}}$.
//! 2. **Scaled SRX Recurrent Core:** $O(1)$ state memory ($H \times 80$ bytes), 100% L1D cache resident.
//! 3. **De-quantizing LM Head:** Continuous hidden state projected to 256-byte vocabulary logits.

use crate::qreno::model::{QrenoConfig, QrenoTokenizer};
use crate::scaled::config::{ScaledConfig, Tier};
use crate::scaled::srx::{
    ScaledSequenceWorkspace, ScaledSrxState, ScaledSrxTransformer, ScaledWorkspace,
};

/// End-to-end continuous quantum language model.
#[derive(Debug, Clone)]
pub struct QrenoSrxLM {
    pub config: ScaledConfig,
    pub tokenizer: QrenoTokenizer,
    pub transformer: ScaledSrxTransformer,
}

impl QrenoSrxLM {
    /// Creates a complete model for a specified architectural tier.
    pub fn new(tier: Tier) -> Self {
        // Vocabulary is 256 pure byte codes
        let config = ScaledConfig::from_tier(tier, 256);
        let qreno_cfg = QrenoConfig {
            field_dim: 8,
            d_model: config.d_model,
            max_cluster_len: 16,
            bond_threshold: 0.5,
            rms_eps: config.rms_eps,
        };

        let tokenizer = QrenoTokenizer::new(qreno_cfg);
        let transformer = ScaledSrxTransformer::new(config.clone());

        Self {
            config,
            tokenizer,
            transformer,
        }
    }

    /// Initializes a blank $O(1)$ L1D-resident recurrent state.
    pub fn init_state(&self) -> ScaledSrxState {
        ScaledSrxState::new(self.config.n_heads)
    }

    /// Allocates an execution workspace scratchpad.
    pub fn new_workspace(&self) -> ScaledWorkspace {
        ScaledWorkspace::new(&self.config)
    }

    /// Processes a single contiguous byte cluster:
    /// Q-RENO field embedding $\to$ Scaled SRX step $\to$ 256-byte logits.
    #[inline(always)]
    pub fn step_cluster(
        &self,
        cluster_bytes: &[u8],
        state: &mut ScaledSrxState,
        logits_out: &mut [f32],
        ws: &mut ScaledWorkspace,
    ) {
        debug_assert_eq!(logits_out.len(), 256);

        // 1. Q-RENO continuous quasi-particle measurement
        let mut emb = vec![0.0f32; self.config.d_model];
        self.tokenizer.embed_cluster_bytes(cluster_bytes, &mut emb);

        // 2. Scaled SRX Transformer recurrent step
        self.transformer.step(&emb, state, logits_out, ws);
    }

    /// Processes a complete UTF-8 string, producing a sequence of byte logit distributions.
    pub fn forward_text(
        &self,
        text: &str,
        state: &mut ScaledSrxState,
        ws: &mut ScaledWorkspace,
    ) -> Vec<Vec<f32>> {
        let clusters = self.tokenizer.tokenize_to_clusters(text);
        let bytes = text.as_bytes();
        let mut all_logits = Vec::with_capacity(clusters.len());

        for c in clusters {
            let cluster_bytes = &bytes[c.start..c.start + c.len];
            let mut logits = vec![0.0f32; 256];
            self.step_cluster(cluster_bytes, state, &mut logits, ws);
            all_logits.push(logits);
        }

        all_logits
    }

    /// Generates continuation bytes autoregressively.
    pub fn generate_bytes(
        &self,
        prompt: &str,
        max_bytes: usize,
        ws: &mut ScaledWorkspace,
    ) -> Vec<u8> {
        let mut state = self.init_state();
        let mut logits = vec![0.0f32; 256];

        // Ingest prompt byte-by-byte
        let prompt_bytes = prompt.as_bytes();
        for &b in prompt_bytes {
            self.step_cluster(&[b], &mut state, &mut logits, ws);
        }

        let mut generated = Vec::with_capacity(max_bytes);
        for _ in 0..max_bytes {
            // Greedy argmax selection
            let mut best_byte = 0u8;
            let mut max_logit = f32::NEG_INFINITY;
            for b in 0..256 {
                if logits[b] > max_logit {
                    max_logit = logits[b];
                    best_byte = b as u8;
                }
            }

            if best_byte == 0 || best_byte == b'\n' {
                break;
            }

            generated.push(best_byte);
            if generated.ends_with(b"<eos>") {
                break;
            }
            // Autoregressive feedback of generated byte
            self.step_cluster(&[best_byte], &mut state, &mut logits, ws);
        }

        generated
    }

    /// Generates continuation bytes autoregressively using temperature, top-k, and repetition penalty.
    pub fn generate_sampled(
        &self,
        prompt: &str,
        max_bytes: usize,
        cfg: &crate::scaled::generator::SamplingConfig,
        rng: &mut crate::scaled::generator::FastRng,
        ws: &mut ScaledWorkspace,
    ) -> Vec<u8> {
        let mut state = self.init_state();
        let mut logits = vec![0.0f32; 256];

        // Ingest prompt via physical quantum clusters
        let mut ssh_ws = crate::qreno::segmenter::SshLatticeWorkspace::new();
        let clusters = self.tokenizer.tokenize_physical(prompt, &mut ssh_ws);
        let prompt_bytes = prompt.as_bytes();

        if clusters.is_empty() {
            for &b in prompt_bytes {
                self.step_cluster(&[b], &mut state, &mut logits, ws);
            }
        } else {
            for c in clusters {
                let slice = &prompt_bytes[c.start..c.start + c.len];
                self.step_cluster(slice, &mut state, &mut logits, ws);
            }
        }

        let mut generated = Vec::with_capacity(max_bytes);
        let mut recent_tokens = Vec::with_capacity(max_bytes);

        for _ in 0..max_bytes {
            let mut l_copy = logits.clone();
            let chosen_b = crate::scaled::generator::sample_token(
                &mut l_copy,
                &recent_tokens,
                cfg,
                rng,
            ) as u8;

            if chosen_b == 0 || chosen_b == b'\n' {
                break;
            }

            generated.push(chosen_b);
            if generated.ends_with(b"<eos>") {
                break;
            }
            recent_tokens.push(chosen_b as usize);

            // Autoregressive feedback
            self.step_cluster(&[chosen_b], &mut state, &mut logits, ws);
        }

        generated
    }

    /// Total parameter count across Q-RENO frontend and Scaled SRX core.
    pub fn param_count(&self) -> usize {
        self.tokenizer.weights.param_count() + self.transformer.param_count()
    }

    /// Executes single forward and analytical backward step on a single byte cluster.
    /// Accumulates gradients into both SRX transformer layers and Q-RENO field parameters.
    /// Returns the cross-entropy loss.
    pub fn train_step_cluster(
        &mut self,
        cluster_bytes: &[u8],
        target_b: usize,
        state: &mut ScaledSrxState,
        ws: &mut ScaledWorkspace,
        qreno_grad: &mut crate::qreno::model::QrenoGrad,
    ) -> f32 {
        let mut emb = vec![0.0f32; self.config.d_model];
        self.tokenizer.embed_cluster_bytes(cluster_bytes, &mut emb);

        let (loss, d_emb) = self.transformer.train_step_emb(&emb, target_b, state, ws);

        self.tokenizer.forward_backward_cluster(cluster_bytes, &d_emb, qreno_grad);

        loss
    }

    /// Allocates a sequence-level BPTT workspace scratchpad.
    pub fn new_sequence_workspace(&self, max_len: usize) -> ScaledSequenceWorkspace {
        ScaledSequenceWorkspace::new(&self.config, max_len)
    }

    /// Trains the model on an entire sequence with exact analytical reverse-time BPTT.
    /// Accumulates gradients into both SRX transformer layers and Q-RENO field parameters.
    /// Returns the mean cross-entropy loss over the sequence.
    pub fn train_sequence(
        &mut self,
        bytes: &[u8],
        ws: &mut ScaledSequenceWorkspace,
        qreno_grad: &mut crate::qreno::model::QrenoGrad,
    ) -> f32 {
        let n_steps = bytes.len() - 1;
        assert!(n_steps > 0);
        assert!(n_steps <= ws.max_len);

        let dm = self.config.d_model;
        let mut embeddings = vec![0.0f32; n_steps * dm];
        let mut targets = vec![0usize; n_steps];

        for t in 0..n_steps {
            let in_b = bytes[t];
            targets[t] = bytes[t + 1] as usize;
            self.tokenizer.embed_cluster_bytes(&[in_b], &mut embeddings[t * dm..(t + 1) * dm]);
        }

        let loss = self.transformer.forward_sequence(&embeddings, &targets, n_steps, ws);

        let mut d_embeddings = vec![0.0f32; n_steps * dm];
        self.transformer.backward_sequence(n_steps, &targets, ws, &mut d_embeddings);

        for t in 0..n_steps {
            let in_b = bytes[t];
            self.tokenizer.forward_backward_cluster(&[in_b], &d_embeddings[t * dm..(t + 1) * dm], qreno_grad);
        }

        loss
    }

    /// Saves all model weights (Q-RENO frontend + Scaled SRX core) to a binary file.
    pub fn save_weights<P: AsRef<std::path::Path>>(&self, path: P) -> std::io::Result<()> {
        use std::io::Write;
        let mut file = std::fs::File::create(path)?;
        file.write_all(b"QSRX")?; // 4 magic bytes
        file.write_all(&1u32.to_le_bytes())?; // version 1
        file.write_all(&(self.config.n_heads as u32).to_le_bytes())?;
        file.write_all(&(self.config.d_model as u32).to_le_bytes())?;

        // Q-RENO weights
        for &w in &self.tokenizer.weights.field.charges { file.write_all(&w.to_le_bytes())?; }
        for &w in &self.tokenizer.weights.field.epsilon { file.write_all(&w.to_le_bytes())?; }
        for &w in &self.tokenizer.weights.field.omega { file.write_all(&w.to_le_bytes())?; }
        for &w in &self.tokenizer.weights.bond.w_bond { file.write_all(&w.to_le_bytes())?; }
        file.write_all(&self.tokenizer.weights.bond.b_bond.to_le_bytes())?;
        for &w in &self.tokenizer.weights.measure.w_o { file.write_all(&w.to_le_bytes())?; }

        // Transformer weights
        let layers = [
            &self.transformer.embed.weight[..],
            &self.transformer.norm_attn.weight[..],
            &self.transformer.attn.w_q.weight[..],
            &self.transformer.attn.w_k.weight[..],
            &self.transformer.attn.w_v.weight[..],
            &self.transformer.attn.w_o.weight[..],
            &self.transformer.norm_ffn.weight[..],
            &self.transformer.ffn.w1.weight[..],
            &self.transformer.ffn.w2.weight[..],
            &self.transformer.norm_final.weight[..],
            &self.transformer.lm_head.weight[..],
        ];
        for l in layers {
            for &w in l {
                file.write_all(&w.to_le_bytes())?;
            }
        }
        file.flush()?;
        Ok(())
    }

    /// Loads model weights from a binary file.
    pub fn load_weights<P: AsRef<std::path::Path>>(&mut self, path: P) -> std::io::Result<()> {
        use std::io::Read;
        let mut file = std::fs::File::open(path)?;
        let mut magic = [0u8; 4];
        file.read_exact(&mut magic)?;
        if &magic != b"QSRX" {
            return Err(std::io::Error::new(std::io::ErrorKind::InvalidData, "Invalid magic bytes for QSRX"));
        }
        let mut u32_buf = [0u8; 4];
        file.read_exact(&mut u32_buf)?; // version
        file.read_exact(&mut u32_buf)?; // n_heads
        file.read_exact(&mut u32_buf)?; // d_model

        let read_f32 = |f: &mut std::fs::File| -> std::io::Result<f32> {
            let mut buf = [0u8; 4];
            f.read_exact(&mut buf)?;
            Ok(f32::from_le_bytes(buf))
        };

        for w in &mut self.tokenizer.weights.field.charges { *w = read_f32(&mut file)?; }
        for w in &mut self.tokenizer.weights.field.epsilon { *w = read_f32(&mut file)?; }
        for w in &mut self.tokenizer.weights.field.omega { *w = read_f32(&mut file)?; }
        for w in &mut self.tokenizer.weights.bond.w_bond { *w = read_f32(&mut file)?; }
        self.tokenizer.weights.bond.b_bond = read_f32(&mut file)?;
        for w in &mut self.tokenizer.weights.measure.w_o { *w = read_f32(&mut file)?; }

        let mut layers = self.transformer.get_layers_mut();
        for (w_slice, _) in layers.iter_mut() {
            for w in w_slice.iter_mut() {
                *w = read_f32(&mut file)?;
            }
        }
        Ok(())
    }
}

