//! # End-to-End Quantum Language Model: Q-RENO Frontend + Scaled SRX Core
//!
//! Integrates:
//! 1. **Q-RENO Continuous Field Frontend:** Converts UTF-8 byte stream into topological quasi-particles $E_m \in \mathbb{R}^{d_{\text{model}}}$.
//! 2. **Scaled SRX Recurrent Core:** $O(1)$ state memory ($H \times 80$ bytes), 100% L1D cache resident.
//! 3. **De-quantizing LM Head:** Continuous hidden state projected to 256-byte vocabulary logits.

use crate::qreno::model::{QrenoConfig, QrenoTokenizer};
use crate::scaled::config::{ScaledConfig, Tier};
use crate::scaled::srx::{ScaledSrxState, ScaledSrxTransformer, ScaledWorkspace};

/// End-to-end continuous quantum language model.
#[derive(Debug, Clone)]
pub struct QrenoSrxLM {
    pub config: ScaledConfig,
    pub tokenizer: QrenoTokenizer,
    pub transformer: ScaledSrxTransformer,
}

impl QrenoSrxLM {
    /// Creates a complete model for a specified architectural tier.
    pub fn new(tier: Tier) -> Self {
        // Vocabulary is 256 pure byte codes
        let config = ScaledConfig::from_tier(tier, 256);
        let qreno_cfg = QrenoConfig {
            field_dim: 8,
            d_model: config.d_model,
            max_cluster_len: 16,
            bond_threshold: 0.5,
            rms_eps: config.rms_eps,
        };

        let tokenizer = QrenoTokenizer::new(qreno_cfg);
        let transformer = ScaledSrxTransformer::new(config.clone());

        Self {
            config,
            tokenizer,
            transformer,
        }
    }

    /// Initializes a blank $O(1)$ L1D-resident recurrent state.
    pub fn init_state(&self) -> ScaledSrxState {
        ScaledSrxState::new(self.config.n_heads)
    }

    /// Allocates an execution workspace scratchpad.
    pub fn new_workspace(&self) -> ScaledWorkspace {
        ScaledWorkspace::new(&self.config)
    }

    /// Processes a single contiguous byte cluster:
    /// Q-RENO field embedding $\to$ Scaled SRX step $\to$ 256-byte logits.
    #[inline(always)]
    pub fn step_cluster(
        &self,
        cluster_bytes: &[u8],
        state: &mut ScaledSrxState,
        logits_out: &mut [f32],
        ws: &mut ScaledWorkspace,
    ) {
        debug_assert_eq!(logits_out.len(), 256);

        // 1. Q-RENO continuous quasi-particle measurement
        let mut emb = vec![0.0f32; self.config.d_model];
        self.tokenizer.embed_cluster_bytes(cluster_bytes, &mut emb);

        // 2. Scaled SRX Transformer recurrent step
        self.transformer.step(&emb, state, logits_out, ws);
    }

    /// Processes a complete UTF-8 string, producing a sequence of byte logit distributions.
    pub fn forward_text(
        &self,
        text: &str,
        state: &mut ScaledSrxState,
        ws: &mut ScaledWorkspace,
    ) -> Vec<Vec<f32>> {
        let clusters = self.tokenizer.tokenize_to_clusters(text);
        let bytes = text.as_bytes();
        let mut all_logits = Vec::with_capacity(clusters.len());

        for c in clusters {
            let cluster_bytes = &bytes[c.start..c.start + c.len];
            let mut logits = vec![0.0f32; 256];
            self.step_cluster(cluster_bytes, state, &mut logits, ws);
            all_logits.push(logits);
        }

        all_logits
    }

    /// Generates continuation bytes autoregressively.
    pub fn generate_bytes(
        &self,
        prompt: &str,
        max_bytes: usize,
        ws: &mut ScaledWorkspace,
    ) -> Vec<u8> {
        let mut state = self.init_state();
        let mut logits = vec![0.0f32; 256];

        // Ingest prompt byte-by-byte
        let prompt_bytes = prompt.as_bytes();
        for &b in prompt_bytes {
            self.step_cluster(&[b], &mut state, &mut logits, ws);
        }

        let mut generated = Vec::with_capacity(max_bytes);
        for _ in 0..max_bytes {
            // Greedy argmax selection
            let mut best_byte = 0u8;
            let mut max_logit = f32::NEG_INFINITY;
            for b in 0..256 {
                if logits[b] > max_logit {
                    max_logit = logits[b];
                    best_byte = b as u8;
                }
            }

            if best_byte == 0 || best_byte == b'\n' {
                break;
            }

            generated.push(best_byte);
            // Autoregressive feedback of generated byte
            self.step_cluster(&[best_byte], &mut state, &mut logits, ws);
        }

        generated
    }

    /// Total parameter count across Q-RENO frontend and Scaled SRX core.
    pub fn param_count(&self) -> usize {
        self.tokenizer.weights.param_count() + self.transformer.param_count()
    }

    /// Executes single forward and analytical backward step on a single byte cluster.
    /// Accumulates gradients into both SRX transformer layers and Q-RENO field parameters.
    /// Returns the cross-entropy loss.
    pub fn train_step_cluster(
        &mut self,
        cluster_bytes: &[u8],
        target_b: usize,
        state: &mut ScaledSrxState,
        ws: &mut ScaledWorkspace,
        qreno_grad: &mut crate::qreno::model::QrenoGrad,
    ) -> f32 {
        let mut emb = vec![0.0f32; self.config.d_model];
        self.tokenizer.embed_cluster_bytes(cluster_bytes, &mut emb);

        let (loss, d_emb) = self.transformer.train_step_emb(&emb, target_b, state, ws);

        self.tokenizer.forward_backward_cluster(cluster_bytes, &d_emb, qreno_grad);

        loss
    }
}
